### ISSUE TITLE
Identifier directly after number

### ISSUE THREAD

**Issue by RomSribn** [sanity-io/contentful-to-sanity#10]
I Recieve the error when I try to run the contentful-to-sanity migration tool.

 It seems like, cases with id that started from numeric variables - not covered, at all. Here are  the error message that might be helpful from the created schema file (created with contentful-to-sanity)

```Creating schema definitions
SynSyntaxError: Identifier directly after number (74:31)
  72 | export default createSchema({
  73 |   name: 'default',
> 74 |   types: schemaTypes.concat([2PqfXUJwE8qSYKuM0U6w8M, SFzTZbSuM8coEwygeUYes, 6XwpTaSiiI2Ak2Ww0oi6qa, 2C4Vf04Sn6yM4iSKAEEIcW, 5Iq0WgjphSei2ywoG6QA4e, 4ouAGlpdUIO6YimUi4yy4c... ])
     |                               ^
  75 | })
  76 |
    at e (/Users/user/Documents/contentful-to-sanity/node_modules/prettier/parser-babylon.js:1:282)
    at Object.parse (/Users/user/Documents/contentful-to-sanity/node_modules/prettier/parser-babylon.js:1:262260)
    at Object.parse (/Users/user/Documents/contentful-to-sanity/node_modules/prettier/index.js:9739:19)
    at coreFormat (/Users/user/Documents/contentful-to-sanity/node_modules/prettier/index.js:13252:23)
    at format (/Users/user/Documents/contentful-to-sanity/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (/Users/user/Documents/contentful-to-sanity/node_modules/prettier/index.js:13526:12)
    at /Users/user/Documents/contentful-to-sanity/node_modules/prettier/index.js:44207:15
    at Object.format (/Users/user/Documents/contentful-to-sanity/node_modules/prettier/index.js:44226:12)
    at format (/Users/user/Documents/contentful-to-sanity/src/createSanitySchema.js:48:21)
    at createSanitySchema (/Users/user/Documents/contentful-to-sanity/src/createSanitySchema.js:44:16)
    at migrate (/Users/user/Documents/contentful-to-sanity/src/migrate.js:40:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async run (/Users/user/Documents/contentful-to-sanity/src/cli.js:354:5)
error Command failed with exit code 1.
```
I did solution like this:
file: `contentful-to-sanity/src/createSanitySchema.js`

```
function createSanitySchema(types, options = {}) {
  const typeNames = types.map((type) => generateValidId(type.name));
  const typeImports = typeNames.map(generateImport).join("\n");
  const typeArray = typeNames.join(", ");
  const prettierOptions = Object.assign(
    {},
    defaultPrettierOptions,
    options.prettierOptions
  );....}

....function generateValidId(typeName) {
  return +typeName[0] ? `A${typeName}` : upperFirst(typeName);
}
```
Work fine for me.

**Comment by runeb** [comment]
Hi @RomSribn. I can't seem to reproduce this because Contentful will not let me create content types with identifiers starting with numbers. Can you share some more information on how you got content types with identifiers like `2PqfXUJwE8qSYKuM0U6w8M`? Legacy (old) space maybe?
