### ISSUE TITLE
Error with Cloudinary object field

### ISSUE THREAD

**Issue by rcobiella** [sanity-io/contentful-to-sanity#18]
Hey! I hope you're doing well, and thank you so much for your work on this plugin.

I just jumped into this error while exporting a space. The field in question is an object field that's using the official Contentful Cloudinary app. It's really just this specific field though, is there a way to skip certain fields to prevent errors?

`✖ Transforming schema
Error: Unhandled data type "Object" with widget "zjcnWgBknf9zB7IM9HZjE" for field "videoCloudinary" of type "blockMediaBlock"
    at contentfulTypeToSanityType (/Users/rcobiella/.config/yarn/global/node_modules/contentful-to-sanity/src/transformSchema.js:202:9)
    at /Users/rcobiella/.config/yarn/global/node_modules/contentful-to-sanity/src/transformSchema.js:116:9
    at Array.map (<anonymous>)
    at transformContentType (/Users/rcobiella/.config/yarn/global/node_modules/contentful-to-sanity/src/transformSchema.js:107:6)
    at /Users/rcobiella/.config/yarn/global/node_modules/contentful-to-sanity/src/transformSchema.js:86:5
    at Array.map (<anonymous>)
    at transformSchema (/Users/rcobiella/.config/yarn/global/node_modules/contentful-to-sanity/src/transformSchema.js:85:42)
    at migrate (/Users/rcobiella/.config/yarn/global/node_modules/contentful-to-sanity/src/migrate.js:34:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async run (/Users/rcobiella/.config/yarn/global/node_modules/contentful-to-sanity/src/cli.js:362:5)`

**Comment by runeb** [comment]
Hi @rcobiella. Are you able to share an export that has this field included? Like our test fixtures here https://github.com/sanity-io/contentful-to-sanity/tree/main/src/test/fixtures

**Comment by rcobiella** [comment]
Some of the data is private, so I just sent it to you on the Sanity Slack.

I just ran it again (first try since your latest update) and got a different error:

```
   ~/Work/2023/contentful-to-sanity-main  cd ./migrate && npx sanity dataset import ./dataset.ndjson                                                                                                                                             ✔  took 53s   base   16.17.1   2.7.0   at 09:42:56  
✔ [100%] Fetching available datasets
? Select target dataset production
✔ [100%] Reading/validating data file (130ms)
✔ [100%] Importing documents (8.87s)
✔ [100%] Importing assets (files/images) (41.84s)
✔ [100%] Setting asset references to documents (5.80s)
✖ [ 15%] Strengthening references (7.88s)

Error: Mutation(s) failed with 1 error(s)
    at onResponse (~/Work/2023/contentful-to-sanity-main/migrate/node_modules/@sanity/cli/lib/_chunks/loadEnv-5068c0c6.js:1666:13)
    at applyMiddleware (~/Work/2023/contentful-to-sanity-main/migrate/node_modules/get-it/dist/index.cjs:60:15)
    at onResponse (~/Work/2023/contentful-to-sanity-main/migrate/node_modules/get-it/dist/index.cjs:133:22)
    at ~/Work/2023/contentful-to-sanity-main/migrate/node_modules/get-it/dist/index.cjs:115:55
    at callback (~/Work/2023/contentful-to-sanity-main/migrate/node_modules/get-it/dist/index.cjs:423:46)
    at ~/Work/2023/contentful-to-sanity-main/migrate/node_modules/get-it/dist/index.cjs:486:14
    at DestroyableTransform.<anonymous> (~/Work/2023/contentful-to-sanity-main/migrate/node_modules/get-it/dist/index.cjs:260:13)
    at Object.onceWrapper (node:events:627:28)
    at DestroyableTransform.emit (node:events:525:35)
    at endReadableNT (~/Work/2023/contentful-to-sanity-main/migrate/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:1010:12)

    ~/Work/2023/contentful-to-sanity-main/migrate  on   main ?3        
 
```

**Comment by runeb** [comment]
@rcobiella Thank you! I am currently looking into this error

**Comment by runeb** [comment]
This shoul be fixed on the upcoming release. We now preserve JSON blobs from contentful as strings. Please re-open this if more issues are encountered after testing the next release
